### PR TITLE
Translatable

### PR DESCRIPTION
**Pull request by MarceauKa**
PHP and JS terms are translatable.
Added english (based on old terms) and french translation.

### CODE REVIEW

**Comment by christophrumpel** [comment]
Hey @MarceauKa, thanks a lot!

Have you run the phpunit tests as well to check if everything is still working? Haven't set the automatically test up year on the repo.

**Comment by MarceauKa** [comment]
ᕦ( ͡° ͜ʖ ͡°)ᕤ

Nope.

**Comment by christophrumpel** [comment]
I took care of that. Thanks man.

**Comment by MarceauKa** [comment]
Don't forget to tag it 1.0.3 👍

**Comment by christophrumpel** [comment]
Ah right. Wanted to wait for style ci changes, but they are already in 👍

**Pull request merged**
